version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - api