version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  #  volumes: 
  #    - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - api-net
networks:
  api-net:
    name: api-net
    driver: bridge
    external: true