version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - api-net
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  api-net:
    name: api-net
    driver: bridge
    external: true