name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh comands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          script: |
            mkdir newFrontend && cd newFrontend
            eval 'ssh-agent -s'
            ssh-add /root/.ssh/git
            git clone git@github.com:Zapchasti-garant/frontend.git
            npm i
            npm run build
            cd ../
            rm -rf frontend
            cp -r ./newFrontend/frontend .
            rm -rf newFrontend
            cd frontend
            docker-compose up --build -d            
